plugins {
    id "com.gradleup.shadow"

    id "com.modrinth.minotaur"
    id "com.matthewprenger.cursegradle"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api}"

    modImplementation include("eu.midnightdust:midnightlib:${rootProject.midnightlib}-fabric")

    // Development QoL
    modLocalRuntime "com.terraformersmc:modmenu:${rootProject.modmenu}"

    // Dependencies
    def path = "${project.parent.path}:common" // Get the correct path, even if we are in a multiproject setup
    common(project(path: path, configuration: "namedElements")) { transitive = false }
    shadowBundle(project(path: path, configuration: "transformProductionFabric"))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabricmc.mod.json') {
        expand version: inputs.properties.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

modrinth {
    debugMode = providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null

    token = providers.environmentVariable("MODRINTH_TOKEN").getOrElse("")

    projectId = 'rideableravagers'
    versionNumber = version
    versionName = "RideableRavagers-${version}"
    versionType = 'release'
    file = remapJar.archiveFile
    changelog = project.file('../CHANGELOG.md').text
    gameVersions = [project.minecraft_version]
    loaders = ['fabric']
    detectLoaders = false

    dependencies {
        // A special DSL for creating dependencies
        // scope.type
        // The scope can be `required`, `optional`, `incompatible`, or `embedded`
        // The type can either be `project` or `version`
        required.project "fabric-api"
        embedded.project "midnightlib"
    }
}

curseforge {
    curseGradleOptions.debug = providers.environmentVariable("CURSEFORGE_TOKEN").getOrNull() == null

    apiKey = providers.environmentVariable("CURSEFORGE_TOKEN").getOrElse("")

    curseGradleOptions.javaIntegration = false
    curseGradleOptions.forgeGradleIntegration = false
    curseGradleOptions.javaVersionAutoDetect = false

    //noinspection GroovyAssignabilityCheck
    project {
        id = '928703'
        releaseType = 'release'
        changelogType = 'markdown'
        changelog = project.file('../CHANGELOG.md')

        addGameVersion project.minecraft_version
        addGameVersion 'Fabric'

        mainArtifact(remapJar) {
            displayName = "RideableRavagers-${version}"
        }

        relations {
            requiredDependency 'fabric-api'
            embeddedLibrary 'midnightlib'
        }
    }
}