plugins {
    id "architectury-plugin" version "${architectury_plugin}"
    id "dev.architectury.loom" version "${architectury_loom}" apply false
    id "com.gradleup.shadow" version "${shadow}" apply false

    id "com.modrinth.minotaur" version "${minotaur}" apply false
    id "com.matthewprenger.cursegradle" version "${cursegradle}" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

allprojects {
    group = project.maven_group
    version = "${project.mod_version}+${rootProject.minecraft_version}-${project.name}"
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = project.mod_name
    }

    repositories {
        maven { url = "https://maven.terraformersmc.com/releases/" } // Mod Menu
        maven { url = "https://maven.midnightdust.eu/releases" } // MidnightLib
    }

    // Disabled due to causing issues in multiproject setup
    // loom {
    //     silentMojangMappingsLicense()
    // }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.officialMojangMappings()

        compileOnly "org.jetbrains:annotations:24.0.1"
        implementation "com.google.code.findbugs:jsr305:3.0.1"
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.getRelease().set(21)
    }

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_name}" }
        }

        manifest {
            attributes([
                    'Specification-Title'     : mod_name,
                    'Specification-Vendor'    : mod_author,
                    'Specification-Version'   : project.version,
                    'Implementation-Title'    : mod_name,
                    'Implementation-Version'  : project.version,
                    'Implementation-Vendor'   : mod_author,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'Timestamp'               : System.currentTimeMillis(),
                    'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                    'Built-On-Minecraft'      : rootProject.minecraft_version
            ])
        }
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Add repositories to publish to here.
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}
