# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradke.parallel=true

# Mod Properties
enabled_platforms = fabric,forge
maven_group = org.github.salandora.rideableravagers

mod_id = rideableravagers
mod_name = RideableRavagers
mod_version = 1.0.2
mod_author = Salandora
mod_license = GNU-AGPL-v3.0

architectury_plugin = 3.4-SNAPSHOT
architectury_loom = 1.13-SNAPSHOT
shadow = 8.3.6
minotaur = 2.8.4
cursegradle = 1.4.0

minecraft_version = 1.20.1
fabric_loader = 0.18.1
fabric_api = 0.89.3+1.20.1
forge = 1.20.1-47.2.1
neoforge = 1.20.1-47.1.79

modmenu = 7.2.2
midnightlib = 1.9.1+1.20.1