# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradke.parallel=true

# Mod Properties
enabled_platforms = fabric,forge
maven_group = org.github.salandora

mod_id = rideableravagers
mod_name = RideableRavagers
mod_version = 1.0.2
mod_author = Salandora
mod_license = GNU-AGPL-v3.0
