pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = "Architectury"
            url = "https://maven.architectury.dev/"
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = "PaperMC"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
    }
}

rootProject.name = "RideableRavagers"

include("common")
include("fabric")
include("neoforge")
include("forge")