modLoader="javafml"
loaderVersion="[47,)"
license="GNU-AGPL-v3.0"

[[mods]]
modId="rideableravagers"
version="${version}"
displayName="RideableRavagers"
logoFile="assets/rideableravagers/icon.png"
authors="Salandora"
description='''Enables you to breed ravagers and ride the tamed ones'''

[[dependencies.rideableravagers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rideableravagers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.rideableravagers]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.1,)"
ordering = "NONE"
side = "BOTH"